//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human_Computer_Interaction.Models.ETModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSignUp
    {
        public int Id { get; set; }
        public string fullName { get; set; }
        public string Pass { get; set; }
        public string email { get; set; }
        public string ConPassword { get; set; }
    }
}
